In [2]:
#imports for the Current Learning Session
import numpy as np

In [4]:
arr = np.array([0,1,2,3] , dtype = np.float32)
print(repr(arr))

array([0., 1., 2., 3.], dtype=float32)


In [6]:
arr_2 = arr  #This wont copy the array to the variable instead of that it creates reference
print(repr(arr_2))
arr_2[0] = 10
print(repr(arr))

array([10.,  1.,  2.,  3.], dtype=float32)
array([10.,  1.,  2.,  3.], dtype=float32)


In [9]:
#To Convert the Data-type of a Complete np.array()
arr = arr.astype(np.int32)
print(repr(arr))

array([10,  1,  2,  3])


In [16]:
#Example for copy
arr = arr_2.copy()
print(repr(arr_2))
arr = arr.astype(np.int32)
print(repr(arr))

array([10.,  1.,  2.,  3.], dtype=float32)
array([10,  1,  2,  3])


In [31]:
arr = np.arange(0,102,2)
print(repr(arr))

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])


In [39]:
arr = np.linspace(4,12,num =10 , dtype = np.int32, endpoint=False) #endpoint wont include the last Number
print(arr)

[ 4  4  5  6  7  8  8  9 10 11]


In [46]:
arr = np.arange(8)
print(arr)
arr = arr.reshape(4,2) #This will reshape the array into Given Dimension
print(arr)
arr = arr.flatten()    #This will nake the Multidimensional array into 1D array
print(arr)

[0 1 2 3 4 5 6 7]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[0 1 2 3 4 5 6 7]


In [52]:
arr = np.arange(10)
print(arr)
arr = np.reshape(arr, (5,2))
print(arr)
arr = np.transpose(arr)
print(arr)
arr = np.transpose(arr)
print(arr)
print(repr(arr.shape))

[0 1 2 3 4 5 6 7 8 9]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 2 4 6 8]
 [1 3 5 7 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
(5, 2)


In [57]:
arr = np.zeros((3,4) , dtype = np.int32)
print(arr)
arr_2 = np.ones((5,5) , dtype = np.int32)
print(arr_2)


[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [60]:
arr = np.zeros_like(arr_2)
print(arr) # It will Create 5x5 Matrix

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [64]:
arr = np.arange(12)
law = np.reshape(arr, (2,3,2))
print(law.shape)

(2, 3, 2)
